### ISSUE TITLE
Route - Get Sub Groups

### ISSUE THREAD

**Issue by cucucachu** [gma1083/democrewcy#10]
Create route and controller(s) for Get Sub Groups

Specs - https://cucucachu.github.io/democrewcy-documentation/APISpecifications.html#getSubGroups

**Comment by gma1083** [comment]
Created route, controller, unit tests, and Postman test for getting subGroups.  All tests passing.

**Comment by gma1083** [comment]
FIxed errors from newly required Group relationship to Position Definition.
