### ISSUE TITLE
Route - Get Channels

### ISSUE THREAD

**Issue by cucucachu** [gma1083/democrewcy#6]
Create a new route and controller(s).

Specs: https://cucucachu.github.io/democrewcy-documentation/APISpecifications.html#getChannels

Route should return an array containing all Channels the user has access to: the channels tied to any groups the user is in, and any events the user is attending.

**Comment by gma1083** [comment]
Created Channel Controller with getChannels() method to get channels tied to groups and events corresponding to the user given. Created unit tests and routes (tested in Postman). All tests Passing.
