### ISSUE TITLE
Route - Get Direct Messages

### ISSUE THREAD

**Issue by cucucachu** [gma1083/democrewcy#7]
Create new route and controller(s) - Get Direct Messages

Specs: https://cucucachu.github.io/democrewcy-documentation/APISpecifications.html#getDirectMessages

Return an array of all Direct messages (the message boards, not the messages) that a user is a part of.

**Comment by gma1083** [comment]
Created DM controller to return DMs per spec. All tests passing. Route created and tested. All tests passing.
